### ISSUE TITLE
How to use token?

### ISSUE THREAD

**Issue by katopz** [firebase/firebase-token-generator-node#11]
Hi guys,

I try search all over the place but can't find how to use it e.g. chat.
And yes I got token already, Just stuck at then what? 
How to get user from it? How to use it to write some data?

Thanks

**Comment by abeisgreat** [comment]
Hi @katopz,

Take a look at the [Custom Authentication docs](https://www.firebase.com/docs/web/guide/login/custom.html) on the Firebase website. This will walk you through using a Firebase Tokwn to authenticate, write, and secure your data.

**Comment by katopz** [comment]
Cool, Many Thanks @abeisgreat It's my bad I skip reading that one. sry!
