### ISSUE TITLE
Issue on latest version of node (v5.5.0)

### ISSUE THREAD

**Issue by rockwotj** [firebase/firebase-token-generator-node#14]
Hello,

I'm using the firebase token generator and since I've upgraded to node v5.5.0 I (for some secrets) get an invalid signature on the generated JWT. 

I have an example if I could email it. The secret is now invalid and worked with another secret that I generated.

**Comment by robertdimarco** [comment]
@rockwotj Can you reach out directly with a repro? Contact me privately at rob @ firebase.com

**Comment by rockwotj** [comment]
@robertdimarco Nevermind, I can't seem to replicate it now. Thanks for reaching out.
