### ISSUE TITLE
How to deploy the generator on a node js server

### ISSUE THREAD

**Issue by AdrienDC** [firebase/firebase-token-generator-node#16]
Hi,
is it possible to have some hints in order to deploy it on a node.js server? I manage to generate my token locally on client side but I have no idea on how to achieve that from server..

Thanks

**Comment by jwngr** [comment]
You have a bunch of options for deploying Node.js applications, but here are two of the ones I normally use:

* [Heroku](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction)
* [Google Cloud Engine](https://cloud.google.com/nodejs/)

Follow the provided links to learn how to deploy a Node.js application using those services and make sure to include this token generator module in your `package.json`.
