### ISSUE TITLE
Token INVALID (node generator)

### ISSUE THREAD

**Issue by becush** [firebase/firebase-token-generator-node#2]
I know this was an issue for the Java token generator.  Does the Node generator have a similar problem?  See error:

{ [Error: INVALID_TOKEN: Could not parse auth token.] code: 'INVALID_TOKEN' }

**Comment by nazywamsiepawel** [comment]
@mikelehen what was the issue exactly?

**Comment by pablorsk** [comment]
can you share de solution?

Thanks...

**Comment by mikelehen** [comment]
Sorry, that was over 2 years ago.  I don't recall what the issue was.  If you're having issues, please file a new issue with details.
