### ISSUE TITLE
It seems that this code needs an update for Firebase 3

### ISSUE THREAD

**Issue by jrmgx** [firebase/firebase-token-generator-node#21]
isn't it?

**Comment by Pajk** [comment]
I think this `firebase-token'generator` has been deprecated. You can now generate custom token with `auth` module.

https://firebase.google.com/docs/auth/server#create_a_custom_token

**Comment by jrmgx** [comment]
yes you're probably right, but I was using this to generate token on a non nodejs (parse.com) environment  and now I'm kind of stuck. I'll figure out a way :-)

**Comment by alfongj** [comment]
See https://firebase.google.com/docs/auth/server#use_a_jwt_library for minting your own Custom tokens with any JWT minting library.

Please note that there has been a fundamental change on how custom tokens work in v3. Now custom tokens are not directly consumable by the DB. You need to send them to your clients, from there call `FirebaseAuth#signInWithCustomToken()` (or equivalent in other non Java langs), and now you can authenticate against the database.

If your use case was to make direct calls from your server to the database, take a look at https://firebase.google.com/docs/database/server/start#section-account instead :)

**Comment by katowulf** [comment]
Also see `firebase login:ci` and `firebase --token` for some command line tools.
